apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manager
  namespace: system
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /ui(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: manager
            port:
              number: 80
