# permissions for end users to edit webcomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: webcomponent-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: microfrontends-controller
    app.kubernetes.io/part-of: microfrontends-controller
    app.kubernetes.io/managed-by: kustomize
  name: webcomponent-editor-role
rules:
- apiGroups:
  - microfrontend.michalsevcik.dev
  resources:
  - webcomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microfrontend.michalsevcik.dev
  resources:
  - webcomponents/status
  verbs:
  - get
