apiVersion: microfrontend.michalsevcik.dev/v1alpha1
kind: WebComponent
metadata: 
  name: ambulance-ufe
spec:   
  module-uri: http://ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigations:
    - element: ambulance-wl-app 
      path: ambulance-wl
      title: Zoznam čakajúcich
      details:  Zapíšte sa do poradovníka pacientov čakajúcich na vyšetrenie u MuDr. Bobulová
      attributes:
        - name: api-uri
          value: /waiting-list-api
        - name: ambulance
          value: bobulova
      icon: 
        mime: image/svg+xml
        data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2ZXJzaW9uPSIxLjEiIGlkPSJhbWJ1bGFuY2UiIAogICB4PSIwcHgiIHk9IjBweCIgd2lkdGg9IjY0cHgiIGhlaWdodD0iNjRweCIgdmlld0JveD0iLTUwIC01MCA1NTAgNTUwIj4KICAgPHBhdGggc3R5bGU9ImZpbGw6bm9uZTtzdHJva2U6IzAwMDAwMDtzdHJva2Utd2lkdGg6MTA7c3Ryb2tlLWxpbmVjYXA6cm91bmQ7c3Ryb2tlLWxpbmVqb2luOnJvdW5kO3N0cm9rZS1vcGFjaXR5OjE7c3Ryb2tlLW1pdGVybGltaXQ6NDtzdHJva2UtZGFzaGFycmF5Om5vbmUiIGQ9Ik0gMTA3LjQsNDU0LjggMTA3LjAsMjYuMyAzOTAuMywyOS44IDM5Mi43LDQ1NS4wIiAgLz4KICAgPHBhdGggc3R5bGU9ImZpbGw6bm9uZTtzdHJva2U6IzAwMDAwMDtzdHJva2Utd2lkdGg6MTA7c3Ryb2tlLWxpbmVjYXA6YnV0dDtzdHJva2UtbGluZWpvaW46cm91bmQ7c3Ryb2tlLW9wYWNpdHk6MTtzdHJva2UtbWl0ZXJsaW1pdDo0O3N0cm9rZS1kYXNoYXJyYXk6bm9uZSIgIGQ9Ik0gMTA3LjAsIDI2LjMgMzMxLjIsNTEuMyBWIDQ3OS4zIGwgLTIyMy43LC0yNC40IHoiIC8+CiAgIDxwYXRoIHN0eWxlPSJmaWxsOm5vbmU7c3Ryb2tlOiMwMDAwMDA7c3Ryb2tlLXdpZHRoOjU7c3Ryb2tlLWxpbmVjYXA6YnV0dDtzdHJva2UtbGluZWpvaW46cm91bmQ7c3Ryb2tlLW9wYWNpdHk6MTtzdHJva2UtbWl0ZXJsaW1pdDo0O3N0cm9rZS1kYXNoYXJyYXk6bm9uZSIgICBkPSJNIDEzMi40LCA4MC42IDMwMi40LDk4LjIgMzAyLjksMjMyLjAgMTMyLjgsMjEyLjUgWiIgLz4KICAgPHBhdGggc3R5bGU9ImZpbGw6bm9uZTtzdHJva2U6IzAwMDAwMDtzdHJva2Utd2lkdGg6NztzdHJva2UtbGluZWNhcDpidXR0O3N0cm9rZS1saW5lam9pbjptaXRlcjtzdHJva2Utb3BhY2l0eToxO3N0cm9rZS1taXRlcmxpbWl0OjQ7c3Ryb2tlLWRhc2hhcnJheTpub25lIiAgIGQ9Im0gMjc1LjAsMjg0LjggYyAyMy45LDMuNCAyNC40LDguMyAyNC40LDguMyIgIC8+Cjwvc3ZnPg==
  preload: false
  proxy: true
  hash-suffix: v1alpha2