apiVersion: microfrontend.michalsevcik.dev/v1alpha1
kind: WebComponent
metadata: 
  name: msevcik-ambulance-ufe
spec:   
  module-uri: http://msevcik-ambulance-ufe.default/build/ambulance-list.esm.js
  navigations:
    - element: msevcik-ambulance-wl-app
      path: msevcik-ambulance-wl
      title: Zoznam čakajúcich msevcik
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: api-uri
          value: /msevcik-waiting-list-api
        - name: ambulance
          value: bobulova
  preload: false
  proxy: true
  hash-suffix: v1alpha1
